In [1]:
# Ejemplo 1

dias  = int(input("Introduce dias: "))
meses = dias/30
dias = dias % 30
print("Meses = %d Dias %d" % (meses, dias))

Introduce dias: 34
Meses = 1 Dias 4


In [3]:
# Ejemplo 2

salario_base = 1500
bonus_ratio  = 200
comision_ratio = 0.02

num_cameras = int(input("Numero de camaras vendidas: "))
precio = float(input("Introduce el importe total de ventas: "))

bonus = bonus_ratio * num_cameras
comision = comision_ratio * num_cameras * precio

print("Bonus        = %6.2f" % bonus)
print("Comision     = %6.2f" % comision)
print("Salario neto = %6.2f" % (salario_base + bonus + comision))

Numero de camaras vendidas: 10
Introduce el importe total de ventas: 1500
Bonus        = 2000.00
Comision     = 300.00
Salario neto = 3800.00


In [5]:
i = 1
print("-" * 50)
while i < 11:
    n = 1
    while n <= 10:
        print("%4d" % (i * n), end=' ')
        n += 1
    print()
    i += 1
print("-" * 50)

--------------------------------------------------
   1    2    3    4    5    6    7    8    9   10 
   2    4    6    8   10   12   14   16   18   20 
   3    6    9   12   15   18   21   24   27   30 
   4    8   12   16   20   24   28   32   36   40 
   5   10   15   20   25   30   35   40   45   50 
   6   12   18   24   30   36   42   48   54   60 
   7   14   21   28   35   42   49   56   63   70 
   8   16   24   32   40   48   56   64   72   80 
   9   18   27   36   45   54   63   72   81   90 
  10   20   30   40   50   60   70   80   90  100 
--------------------------------------------------


In [6]:
while True:
    n = int(input("Please enter an Integer: "))
    if n < 0:
        continue # this will take the execution back to the starting of the loop
    elif n == 0:
        break
    print("Square is ", n ** 2)
print("Goodbye")

Please enter an Integer: 3
Square is  9
Please enter an Integer: 8
Square is  64
Please enter an Integer: -3
Please enter an Integer: -3
Please enter an Integer: 5
Square is  25
Please enter an Integer: 0
Goodbye


In [7]:
for i in range(0, 5):
    print(i)
else:
    print("Bye bye")

0
1
2
3
4
Bye bye


In [1]:
sticks = 21

print("There are 21 sticks, you can take 1-4 number of sticks at a time.")
print("Whoever will take the last stick will lose")

while True:
    print("Sticks left: " , sticks)
    sticks_taken = int(input("Take sticks(1-4):"))
    
    if sticks == 1:
        print("You took the last stick, you lose")
        break
    
    if sticks_taken >= 5 or sticks_taken <= 0:
        print("Wrong choice")
        continue
        
    print("Computer took: " , (5 - sticks_taken) , "\n")
    sticks -= 5

There are 21 sticks, you can take 1-4 number of sticks at a time.
Whoever will take the last stick will lose
Sticks left:  21
Take sticks(1-4):1
Computer took:  4 

Sticks left:  16
Take sticks(1-4):4
Computer took:  1 

Sticks left:  11
Take sticks(1-4):1
Computer took:  4 

Sticks left:  6
Take sticks(1-4):1
Computer took:  4 

Sticks left:  1
Take sticks(1-4):1
You took the last stick, you lose


In [10]:
data = {'kushal':'Fedora', 'kart_':'Debian', 'Jace':'Mac'}
data

{'kushal': 'Fedora', 'kart_': 'Debian', 'Jace': 'Mac'}

In [11]:
data['kart_']

'Debian'

In [12]:
data['parthan'] = 'Ubuntu'
data

{'kushal': 'Fedora', 'kart_': 'Debian', 'Jace': 'Mac', 'parthan': 'Ubuntu'}

In [13]:
del data['kushal']
data

{'kart_': 'Debian', 'Jace': 'Mac', 'parthan': 'Ubuntu'}

In [14]:
'Soumya' in data

False

In [17]:
for x in data:
    print(f"Key = {x}")

Key = kart_
Key = Jace
Key = parthan


In [18]:
for x, y in data.items():
    print("%s uses %s" % (x, y))

kart_ uses Debian
Jace uses Mac
parthan uses Ubuntu


In [20]:
for i, j in enumerate(['a', 'b', 'c'], start=1):
    print(i, j)

1 a
2 b
3 c


In [21]:
n = int(input("Enter the number of students:"))
data = {} # here we will store the data
languages = ('Physics', 'Maths', 'History') #all languages

for i in range(0, n): #for the n number of students
    name = input('Enter the name of the student %d: ' % (i + 1)) #Get the name of the student
    marks = []

    for x in languages:
        marks.append(int(input('Enter marks of %s: ' % x))) #Get the marks for languages
        data[name] = marks

for x, y in data.items():
    total = sum(y)
    print("%s 's total marks %d" % (x, total))
    
    if total < 15:
        print("%s failed :(" % x)
    else:
        print("%s passed :)" % x)

Enter the number of students:2
Enter the name of the student 1: Juan
Enter marks of Physics: 6
Enter marks of Maths: 7
Enter marks of History: 8
Enter the name of the student 2: Pedro
Enter marks of Physics: 1
Enter marks of Maths: 3
Enter marks of History: 4
Juan 's total marks 21
Juan failed :(
Pedro 's total marks 8
Pedro failed :(


In [22]:
data

{'Juan': [6, 7, 8], 'Pedro': [1, 3, 4]}

In [23]:
languages

('Physics', 'Maths', 'History')

In [1]:
# Converting a one dimension array into a two dimension array
import numpy as np

array = np.arange(8) 

print("Original array : \n", array)

array = np.arange(8).reshape(2, 4)
print("New array : \n", array)

Original array : 
 [0 1 2 3 4 5 6 7]
New array : 
 [[0 1 2 3]
 [4 5 6 7]]


In [2]:
def unknown(*args, **kwargs):
    print(f"We received {len(args)} positional arguments. And they are:")

    for arg in args:
        print(arg, end= " ")
        
    print("")
    print(f"We received {len(kwargs)} keyword arguments. And they are:")

    for k, v in kwargs.items():
        print(f"key={k} and value={v}")

unknown(30, 90, "kushal", lang="python", editor="vim")

We received 3 positional arguments. And they are:
30 90 kushal 
We received 2 keyword arguments. And they are:
key=lang and value=python
key=editor and value=vim


In [1]:
# import required libraries
import pandas as pd
import numpy as np

# creating initial dataframe
bridge_types = ('Arch','Beam','Truss','Cantilever','Tied Arch','Suspension','Cable')
bridge_df = pd.DataFrame(bridge_types, columns=['Bridge_Types'])

# converting type of columns to 'category'
bridge_df['Bridge_Types'] = bridge_df['Bridge_Types'].astype('category')

# Assigning numerical values and storing in another column
bridge_df['Bridge_Types_Cat'] = bridge_df['Bridge_Types'].cat.codes
bridge_df

Bridge_Types  Bridge_Types_Cat
0         Arch                 0
1         Beam                 1
2        Truss                 6
3   Cantilever                 3
4    Tied Arch                 5
5   Suspension                 4
6        Cable                 2

In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

# creating initial dataframe
bridge_types = ('Arch','Beam','Truss','Cantilever','Tied Arch','Suspension','Cable')
bridge_df = pd.DataFrame(bridge_types, columns=['Bridge_Types'])

# creating instance of labelencoder
labelencoder = LabelEncoder()

# Assigning numerical values and storing in another column
bridge_df['Bridge_Types_Cat'] = labelencoder.fit_transform(bridge_df['Bridge_Types'])
bridge_df

Bridge_Types  Bridge_Types_Cat
0         Arch                 0
1         Beam                 1
2        Truss                 6
3   Cantilever                 3
4    Tied Arch                 5
5   Suspension                 4
6        Cable                 2